apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: mq
spec:
  hard:
    requests.cpu: 400m
    requests.memory: 512Mi
    limits.cpu: 400m
    limits.memory: 512Mi
    requests.storage: 10Gi
