apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: mq
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 8Gi
    limits.cpu: 8000m
    limits.memory: 16Gi
    requests.storage: 50Gi
    pods: "10"
