apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: mq
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.cpu: 500m
    limits.memory: 512Mi
    requests.storage: 20Gi
    persistentvolumeclaims: "4"
    pods: "5"
    configmaps: "5"
    secrets: "5"
    services: "5"
    services.loadbalancers: "0"
